name: mserp
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.1
  flutter_bloc: ^9.1.1
  connectivity_plus: ^6.1.4
  http: ^1.4.0
  http_interceptor: ^2.0.0
  dio: ^5.8.0+1
  logger: ^2.6.0
  pretty_dio_logger: ^1.4.0
  freezed_annotation: ^3.1.0
  freezed: ^3.1.0
  shared_preferences: ^2.5.3
  flutter_staggered_grid_view: ^0.7.0
  get: ^4.7.2
  toggle_switch: ^2.3.0
  dooz_color_picker: ^0.1.0
  provider: ^6.1.5+1
  intl: ^0.20.2
  mobile_scanner: ^7.1.3
  dropdown_button2: ^2.3.9
  remixicon: ^1.4.1
  icons_plus: ^5.0.0
  country_picker: ^2.0.27
  image_picker: ^1.2.1
  file_picker: ^10.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.4


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/gif_icons/
    - assets/setting_icons/

